### PR TITLE
Add support for GitHub Enterprise

### PR DESCRIPTION
**Pull request by solvaholic**
I :heart: using [the gist package for Atom](https://atom.io/packages/gist) to create and edit Gists on GitHub.com!

I'd also like to use it to create and edit Gists on my GitHub Enterprise instance.

This PR adds configuration options for a custom hostname and updates README.md.

### CODE REVIEW

**Comment by aki77** [comment]
Thank you for PR!
Do you need hostnameFile setting?
I think it dose not need it.

**Comment by solvaholic** [comment]
You're welcome - Thank you for this excellent package!

I added `hostnameFile` for parity with the `tokenFile` option.

It would be OK to store `hostname` in the configuration file.

Would you prefer I remove the `hostnameFile` option?

**Comment by aki77** [comment]
Please remove it by yourself.
Thanks.

**Comment by aki77** [comment]
Thank you!
0.4.0 has been released.

**Pull request merged**
